### ISSUE TITLE
UI Theme in screenshot?

### ISSUE THREAD

**Issue by joshua** [mmcbride1007/electron-highlighter-syntax#1]
@mmcbride1007 What is the UI Theme in the screenshot?

**Comment by mikemcbride** [comment]
@joshua I'm just using the One Dark UI. Are you seeing something weird?

**Comment by joshua** [comment]
Is the toolbar above the tab bar provided by another package?

**Comment by mikemcbride** [comment]
Ah, yes it is :smiley:

Check out [tool-bar](https://atom.io/packages/tool-bar). That adds an empty toolbar, and then you install another package to configure items within the bar. There are currently two:

[tool-bar-main](https://atom.io/packages/tool-bar-main) which is by the author of tool-bar and gives you a fixed set of actions, and [flex-tool-bar](https://atom.io/packages/flex-tool-bar), which is the one I am using. It's super customizable, and the author has it pretty well documented.

Cheers!

**Comment by joshua** [comment]
Awesome. Thanks!

**Comment by mikemcbride** [comment]
You're quite welcome!
