### ISSUE TITLE
ST theme?

### ISSUE THREAD

**Issue by kengz** [mmcbride1007/electron-highlighter-syntax#2]
Beautiful.

Because of Atom's performance speed (when you're writing 3k or more lines), I'm still using Sublime Text.
Is there a plan to release a ST color theme of this too?

**Comment by mikemcbride** [comment]
Thanks! Glad you're enjoying it :+1: 

I'm not currently planning on porting it to Sublime Text, sorry. I know that the Atom team is hard at work to improve performance and have made huge strides in that area compared to some of the earlier betas. If you haven't tried working in larger files recently you might want to give that a shot again :smile:
