### ISSUE TITLE
Use `.bracket-matcher .region` to select highlighted brackets.

### ISSUE THREAD

**Issue by narayaanir** [mmcbride1007/electron-highlighter-syntax#3]
In index.less: Use `.bracket-matcher .region` to select highlighted brackets.

**Comment by mikemcbride** [comment]
Not sure I follow you here. `index.less` just imports the other partials, and I've already got styles in `editor.less` for `.bracket-matcher .region`. [Check it out here](https://github.com/mmcbride1007/electron-highlighter-syntax/blob/master/styles/editor.less#L23-L27).

Could you elaborate? Are you seeing a bug? Thanks!

**Comment by narayaanir** [comment]
I saw this as a deprecation. Please ignore/close out this issue.

**Comment by mikemcbride** [comment]
Oh gotcha. Thanks!
